import speech_recognition as sr
import os

def obtener(test):
    r = sr.Recognizer()
    with sr.AudioFile(test) as source:
        audio = r.listen(source)
        try:
            text = "Estoy procesando tu consulta"
            os.system("start C:\\analizadorToxic\\Codigo_Fuente\\Audio\\proceso.mp3")
            text = r.recognize_google(audio, language='es-MX').lower()
            text = text.replace('abre paréntesis', '(')
            text = text.replace('cierra paréntesis', ')')
            text = text.replace('abre corchete', '[')
            text = text.replace('cierra corchetes', ']')
            text = text.replace('abre llave', '{\n')
            text = text.replace('cierra llave', '}')
            text = text.replace('letra', '')
            text = text.replace('punto y coma', ';\n')
            text = text.replace('punto', '.')
            text = text.replace('comilla', '\'')
            text = text.replace('coma', ',\n')
            text = text.replace('fin de comentario', '\n')
            text = text.replace('comentario', '$')
            text = text.replace('mayor o igual que', '>=')
            text = text.replace('menor o igual que', '<=')
            text = text.replace('mayor que', '>')
            text = text.replace('menor que', '<')
            text = text.replace('á', 'a')
            text = text.replace('é', 'e')
            text = text.replace('í', 'i')
            text = text.replace('ó', 'o')
            text = text.replace('ú', 'u')
            text = text.replace('sino', 'ELSE')
            text = text.replace('si', 'IF')
            text = text.replace('mas', '+')
            text = text.replace('menos', '-')
            text = text.replace('por', '*')
            text = text.replace('entre', '/')
            text = text.replace('mas igual', '+=')
            text = text.replace('menos igual', '-=')
            text = text.replace('por igual', '*=')
            text = text.replace('entre igual', '/=')
            text = text.replace('diferente', '!=')
            text = text.replace('inicio', 'BGN')
            text = text.replace('fin', 'END')
            text = text.replace('mientras', 'WHL')
            text = text.replace('do', 'DO')
            text = text.replace('procedimiento', 'PCD')
            text = text.replace('llamar', 'CALL')
            text = text.replace('entero', 'INT')
            text = text.replace('flotante', 'FLT')
            text = text.replace('caracter', 'CHR')
            text = text.replace('cadena', 'STR')
            return text
        except:
            print("No se ha encontrado la ruta que indicaste para escribir.")